FROM node:alpine

LABEL mantainer="antoniorr@correo.ugr.es" version="0.0.1"

WORKDIR /app

COPY package.json package-lock.json tienda.js ./
RUN npm install
COPY . .

ENV IN=production
ENV USER_DB=root
ENV PASS=example
ENV SECRET_KEY="EsTa MisMa:i8775tyjk,"
ENV DB_HOST=mongo

ENTRYPOINT ["node", "tienda.js"]
